; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:genericSTM32F407VGT6]
platform = ststm32
board = genericSTM32F407VGT6
framework = arduino
lib_deps = https://github.com/stm32duino/STM32FreeRTOS.git
build_flags =
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -O2
    -DI2C_TIMEOUT_TICK=15
    -DSERIAL_RX_BUFFER_SIZE=256
    -DSERIAL_TX_BUFFER_SIZE=256
monitor_speed = 115200
upload_protocol = stlink
upload_flags =
    -c
    reset_config srst_only srst_nogate connect_assert_srst
